import Navbar from "@/components/shared/Navbar";
import "./globals.css";
import { ibmPlexMono } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ibmPlexMono.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#FFFFFF]">
        <Navbar></Navbar>
        <main>
        {children}
        </main>
        </body>
    </html>
  );
}
